[site]
title="H&Y's Blog"
subtitle="记录H&Y所有一切的博客，包括生活、技术、学习、情感和所有的所有……"
description="生活情感这些，迁移到http://heloveyu.com站去了"
author="puras"
domain="https://puras.cn"
theme="default"

[path]
theme="./themes"
assets="assets"
public="./public"
post="./sources/_posts"
page="./sources/_pages"
timeline="./sources/_timelines"
